export interface IKeyData {
  key: any;
  modifiers: any[];
}

export const KeyCodes: { name: string, value: string }[] = [
  { name: '0', value: 'VK_0' },
  { name: '1', value: 'VK_1' },
  { name: '2', value: 'VK_2' },
  { name: '3', value: 'VK_3' },
  { name: '4', value: 'VK_4' },
  { name: '5', value: 'VK_5' },
  { name: '6', value: 'VK_6' },
  { name: '7', value: 'VK_7' },
  { name: '8', value: 'VK_8' },
  { name: '9', value: 'VK_9' },
  { name: 'A', value: 'VK_A' },
  { name: 'B', value: 'VK_B' },
  { name: 'C', value: 'VK_C' },
  { name: 'D', value: 'VK_D' },
  { name: 'E', value: 'VK_E' },
  { name: 'F', value: 'VK_F' },
  { name: 'G', value: 'VK_G' },
  { name: 'H', value: 'VK_H' },
  { name: 'I', value: 'VK_I' },
  { name: 'J', value: 'VK_J' },
  { name: 'K', value: 'VK_K' },
  { name: 'L', value: 'VK_L' },
  { name: 'M', value: 'VK_M' },
  { name: 'N', value: 'VK_N' },
  { name: 'O', value: 'VK_O' },
  { name: 'P', value: 'VK_P' },
  { name: 'Q', value: 'VK_Q' },
  { name: 'R', value: 'VK_R' },
  { name: 'S', value: 'VK_S' },
  { name: 'T', value: 'VK_T' },
  { name: 'U', value: 'VK_U' },
  { name: 'V', value: 'VK_V' },
  { name: 'W', value: 'VK_W' },
  { name: 'X', value: 'VK_X' },
  { name: 'Y', value: 'VK_Y' },
  { name: 'Z', value: 'VK_Z' },

  { name: 'Numpad 0', value: 'NUMPAD0' },
  { name: 'Numpad 1', value: 'NUMPAD1' },
  { name: 'Numpad 2', value: 'NUMPAD2' },
  { name: 'Numpad 3', value: 'NUMPAD3' },
  { name: 'Numpad 4', value: 'NUMPAD4' },
  { name: 'Numpad 5', value: 'NUMPAD5' },
  { name: 'Numpad 6', value: 'NUMPAD6' },
  { name: 'Numpad 7', value: 'NUMPAD7' },
  { name: 'Numpad 8', value: 'NUMPAD8' },
  { name: 'Numpad 9', value: 'NUMPAD9' },

  { name: 'F1', value: 'F1' },
  { name: 'F2', value: 'F2' },
  { name: 'F3', value: 'F3' },
  { name: 'F4', value: 'F4' },
  { name: 'F5', value: 'F5' },
  { name: 'F6', value: 'F6' },
  { name: 'F7', value: 'F7' },
  { name: 'F8', value: 'F8' },
  { name: 'F9', value: 'F9' },
  { name: 'F10', value: 'F10' },
  { name: 'F11', value: 'F11' },
  { name: 'F12', value: 'F12' },
  { name: 'F13', value: 'F13' },
  { name: 'F14', value: 'F14' },
  { name: 'F15', value: 'F15' },
  { name: 'F16', value: 'F16' },
  { name: 'F17', value: 'F17' },
  { name: 'F18', value: 'F18' },
  { name: 'F19', value: 'F19' },
  { name: 'F20', value: 'F20' },
  { name: 'F21', value: 'F21' },
  { name: 'F22', value: 'F22' },
  { name: 'F23', value: 'F23' },
  { name: 'F24', value: 'F24' },

  { name: 'Mouse left', value: 'LBUTTON' },
  { name: 'Mouse right', value: 'RBUTTON' },
  { name: 'Mouse middle', value: 'MBUTTON' },
  { name: 'Mouse 4', value: 'XBUTTON1' },
  { name: 'Mouse 5', value: 'XBUTTON5' },

  { name: 'Cancel', value: 'CANCEL' },
  { name: 'Back', value: 'BACK' },
  { name: 'Tab', value: 'TAB' },
  { name: 'Clear', value: 'CLEAR' },
  { name: 'Return', value: 'RETURN' },
  { name: 'Menu', value: 'MENU' },
  { name: 'Pause', value: 'PAUSE' },
  { name: 'Esc', value: 'ESCAPE' },
  { name: 'Space', value: 'SPACE' },

  { name: 'Left', value: 'LEFT' },
  { name: 'Right', value: 'RIGHT' },
  { name: 'Up', value: 'UP' },
  { name: 'Down', value: 'DOWN' },

  { name: 'Home', value: 'HOME' },
  { name: 'End', value: 'END' },
  { name: 'Insert', value: 'INSERT' },
  { name: 'Delete', value: 'DELETE' },

  { name: 'Print', value: 'PRINT' },
  { name: 'Windows Left', value: 'LWIN' },
  { name: 'Windows Right', value: 'RWIN' },

  { name: 'Multiply', value: 'MULTIPLY' },
  { name: 'Add', value: 'ADD' },
  { name: 'Separator', value: 'SEPARATOR' },
  { name: 'Substract', value: 'SUBTRACT' },
  { name: 'Decimal', value: 'DECIMAL' },
  { name: 'Divide', value: 'DIVIDE' },
  { name: 'NumLock', value: 'NUMLOCK' },
  { name: 'Scroll', value: 'SCROLL' },
  { name: 'Shift', value: 'SHIFT' },
  { name: 'Shift Left', value: 'LSHIFT' },
  { name: 'Shift Right', value: 'RSHIFT' },
  { name: 'Control', value: 'CONTROL' },
  { name: 'Control Left', value: 'LCONTROL' },
  { name: 'Control Right', value: 'RCONTROL' },
  { name: 'Menu Left', value: 'LMENU' },
  { name: 'Menu Right', value: 'RMENU' },

  { name: 'Volume Mute', value: 'VOLUME_MUTE' },
  { name: 'Volume Down', value: 'VOLUME_DOWN' },
  { name: 'Volume Up', value: 'VOLUME_UP' },

  { name: 'Media Next', value: 'MEDIA_NEXT_TRACK' },
  { name: 'Media Prev', value: 'MEDIA_PREV_TRACK' },
  { name: 'Media Stop', value: 'MEDIA_STOP' },
  { name: 'Media Play/Pause', value: 'MEDIA_PLAY_PAUSE' },

  { name: 'Browser Back', value: 'BROWSER_BACK' },
  { name: 'Browser Forward', value: 'BROWSER_FORWARD' },
  { name: 'Browser Refresh', value: 'BROWSER_REFRESH' },
  { name: 'Browser Stop', value: 'BROWSER_STOP' },
  { name: 'Browser Search', value: 'BROWSER_SEARCH' },
  { name: 'Browser Favorites', value: 'BROWSER_FAVORITES' },
  { name: 'Browser Home', value: 'BROWSER_HOME' },

  { name: 'Apps', value: 'APPS' },
  { name: 'Sleep', value: 'SLEEP' },


  // 'CAPITAL',
  // 'HANGEUL',
  // 'HANGUL',
  // 'KANA',
  // 'JUNJA',
  // 'FINAL',
  // 'HANJA',
  // 'KANJI',
  // 'CONVERT',
  // 'NONCONVERT',
  // 'ACCEPT',
  // 'MODECHANGE',
  // 'PRIOR',
  // 'NEXT',
  // 'SELECT',
  // 'EXECUTE',
  // 'SNAPSHOT',
  // 'HELP',

  // 'LAUNCH_MAIL',
  // 'LAUNCH_MEDIA_SELECT',
  // 'LAUNCH_APP1',
  // 'LAUNCH_APP2',

  // 'OEM_1',
  // 'OEM_PLUS',
  // 'OEM_COMMA',
  // 'OEM_MINUS',
  // 'OEM_PERIOD',
  // 'OEM_2',
  // 'OEM_3',
  // 'OEM_4',
  // 'OEM_5',
  // 'OEM_6',
  // 'OEM_7',
  // 'OEM_8',
  // 'OEM_102',
  // 'PROCESSKEY',
  // 'PACKET',
  // 'ATTN',
  // 'CRSEL',
  // 'EXSEL',
  // 'EREOF',
  // 'PLAY',
  // 'ZOOM',
  // 'NONAME',
  // 'PA1',
  // 'OEM_CLEAR',
];
